version: "3.7"

services:
  web:
    build: ./services/web
    command: python manage.py run -h ${HOST}
    volumes:
      - ./services/web/:/usr/src/app/
    ports:
      - ${WEB_PORTS}
    env_file:
      - ./.env.dev
    depends_on:
      - db
      - es
  db:
    image: postgres:12-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch-platinum:6.2.4
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data 
    environment:
      - "discovery.type=single-node"
      - xpack.security.enabled=${ES_SECURITY_ENABLED}   
    ports:
      - ${ES_REST_PORTS}

volumes:
  postgres_data:
  elasticsearch_data:

