version: "3.7"

services:
  web:
    build: ./services/web
    command: python manage.py run -h 0.0.0.0
    volumes:
      - ./services/web/:/usr/src/app/
    ports:
      - 5000:5000
    env_file:
      - ./.env.dev
    depends_on:
      - db
      - es
  db:
    image: postgres:12-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=pstgrs
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=search_app_dev
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch-platinum:6.2.4
    environment:
      - "discovery.type=single-node"
      - xpack.security.enabled=false    
    ports:
      - 9200:9200

volumes:
  postgres_data:

